# Define Profiles
spring:
  profiles: devfinbet
  redis:
    # host: http://baiwa.ddns.net
    host: localhost
    port: 6379

# Database Connection
main:
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jdbc-url: jdbc:sqlserver://172.19.93.11:1433;databaseName=COFFEE_BEANS;useUnicode=true;characterEncoding=UTF-8
    username: sa
    password: FinnBet2020

# JWT
jwt:
  secret: coffee-secret-key-jwt-api-app
  # 5 hour (5 * 60 * 60)
  time-expire: 18000

customer-file:
  images:
    path: CoffeeBeanImage

secert-key:
  update-lotto: ∆@∂ßπ≠‘“πø¬æ≥≤µ∫Ω≈ç√ƒ∂ß∑†¥¨ˆø£
common-path:
  bo: https://finnbet.com/COFFEE
  img:
    api: https://finnbet.com/COFFEE-FILE

  # kafka
  kafka-url: localhost:9092
